version: "3" 
services:
  # Web service layer
  nginx:
    image: nginx:1.13
    container_name: nginx_gateway_payment
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    depends_on:
      - php
  
  # Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
    container_name: php_gateway_payment
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123456
  
  # Data persistence service layer
  mysql:
    image: mysql:5.7.31
    container_name: mysql_gateway_payment
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

volumes:
  db_data: